# Project: snake
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o snake.o
LINKOBJ  = main.o snake.o
LIBS     = -L"D:/WenJian/Dev-Cpp/MinGW64/lib" -L"D:/WenJian/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"D:/WenJian/Dev-Cpp/MinGW64/include" -I"D:/WenJian/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/WenJian/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/WenJian/Dev-Cpp/MinGW64/include" -I"D:/WenJian/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/WenJian/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/WenJian/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = snake.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

snake.o: snake.cpp
	$(CPP) -c snake.cpp -o snake.o $(CXXFLAGS)
